language: python
python:
  - "2.7"
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink

install:
  - pip install -U https://github.com/platformio/platformio-core/archive/master.zip
  - platformio --version
  - platformio platform install file://.
  - wget https://downloads.ti.com/ccs/esd/tirex/zips/energia_cc13xx_5.20.0/energia_cc13xx_5.20.0__linux.zip
  - mkdir -p ~/.platformio/packages/framework-energiaticc13x0
  - unzip energia_cc13xx_5.20.0__linux.zip -d ~/.platformio/packages/framework-energiaticc13x0
  - ls -lh ~/.platformio/packages/framework-energiaticc13x0

script:
  - platformio run -v -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
