language: python
python:
  - "2.7"
  - "3.6"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink

install:
  - pip install -U https://github.com/platformio/platformio-core/archive/v4.3.4.zip
  - platformio platform install file://.

script:
  - platformio run -v -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
