language: python
python:
  - "2.7"
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink

install:
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
  - platformio --version
  - platformio platform install file://.

script:
  - platformio run -v -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
